### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ademolght** [RocketGod-git/flipper-sub-to-hackrf-portapack-c16-converter#2]
When are you going fix this code ?

**Comment by pir8radio** [comment]
or rather, what is broken about it?  I can try to do some work on it if you no longer want to mess with it.

**Comment by pir8radio** [comment]
looks like someone forked it and it might be working there :https://github.com/medmar22/flipper-sub-to-hackrf-portapack-c16-converter

**Comment by RocketGod-git** [comment]
Hi! I have no plan to fix it right now since I'm working on a couple Portapack apps. I can come back to this when those are done though. I don't think that fork will work but doesn't hurt for you to try it.

**Comment by Ademolght** [comment]
ok np @RocketGod-git

**Comment by pir8radio** [comment]
I'm working on my own fork and so far it's worked for my tests.    I changed a few things to handle recursive folders on the input and output side for mass converting.   I just started modifying last night so hold off on using my fork.   I need to change some things to handle other protocols.
